FROM --platform=linux/amd64 ubuntu:20.04 as builder

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential libz-dev

COPY . /repo
WORKDIR /repo/squashfs-tools
RUN make -j8

FROM ubuntu:20.04 as package
COPY --from=builder /repo/squashfs-tools/mksquashfs /
